version: '3.4'

networks:
    globoticket:

services:
# CATALOG SERVICE
  catalog:
    image: ${DOCKER_REGISTRY-}catalog
    build:
      context: .
      dockerfile: catalog/Dockerfile
    networks:
      - globoticket

  catalog-dapr:
    container_name: "catalog-sidecar"
    image: "daprio/daprd:1.11.3"
    command: [
      "./daprd",
     "-app-id", "catalog",
     "-app-port", "80",
     "-components-path", "/in-container-components",
     "-config", "/in-container-components/config.yaml"
     ]
    volumes:
      - "./components/docker-compose/:/in-container-components"
    depends_on:
      - catalog
    network_mode: "service:catalog"

#FRONTEND SERVICE
  frontend:
    image: ${DOCKER_REGISTRY-}frontend
    build:
      context: .
      dockerfile: frontend/Dockerfile
    networks:
      - globoticket

  frontend-dapr:
    container_name: "frontend-sidecar"
    image: "daprio/daprd:1.11.3"
    command: [
      "./daprd",
     "-app-id", "frontend",
     "-app-port", "80",
     "-components-path", "/in-container-components",
     "-config", "/in-container-components/config.yaml"
     ]
    volumes:
      - "./components/docker-compose/:/in-container-components"
    depends_on:
      - frontend
    network_mode: "service:frontend"

# ORDERING SERVICE
  ordering:
    image: ${DOCKER_REGISTRY-}ordering
    build:
      context: .
      dockerfile: ordering/Dockerfile
    networks:
      - globoticket

  ordering-dapr:
    container_name: "ordering-sidecar"
    image: "daprio/daprd:1.11.3"
    command: [
      "./daprd",
     "-app-id", "ordering",
     "-app-port", "80",
     "-components-path", "/in-container-components",
     "-config", "/in-container-components/config.yaml"
     ]
    volumes:
      - "./components/docker-compose/:/in-container-components"
    depends_on:
      - ordering
    network_mode: "service:ordering"

# DAPR STUFF
  redis:
    container_name: "redis"
    image: "redis:7.2-alpine"
    ports:
      - "6379"
    networks:
      - globoticket
      
  zipkin:
    container_name: "zipkin"
    image: "openzipkin/zipkin:2.24"
    ports:
      - 9412:9411
    networks:
      - globoticket
